// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// is_valid_semver
std::vector < bool > is_valid_semver(std::vector < std::string > v);
RcppExport SEXP _vershist_is_valid_semver(SEXP vSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector < std::string > >::type v(vSEXP);
    rcpp_result_gen = Rcpp::wrap(is_valid_semver(v));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_vershist_is_valid_semver", (DL_FUNC) &_vershist_is_valid_semver, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_vershist(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
