# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Test if semantic version strings are valid
#'
#' @param v character verctor of version strings
#' @export
is_valid <- function(v) {
    .Call('_vershist_is_valid', PACKAGE = 'vershist', v)
}

